### ISSUE TITLE
O que isso faz?

### ISSUE THREAD

**Issue by felipesuri** [portothree/dotfiles#1]
Estava navegando pelos suus arquivos, porém não está bem claro certas coisas, o que o "lemonbar" faz?

**Comment by portothree** [comment]
Opa @felipesuri, [lemonbar](https://github.com/LemonBoy/bar) é uma barra de tarefas, no meu script `barf.sh` há funções para por exemplo checar o nivel da bateria do meu notebook e mostrar na barra ativa.

É basicamente uma board preta que pode receber valores, no meu caso retornam das funções no arquivo `.sh`. Existem também outras opções como o [PolyBar](https://github.com/polybar/polybar), gosto do lemonbar por ser escrito em C e ser mais modular.
